### ISSUE TITLE
question

### ISSUE THREAD

**Issue by vensun41** [KIT-IBT/LDRB_Fibers#2]
Thank you for sharing, and I would like to ask how these files are generated from the INP file of abaqus. Thank you very much
![屏幕截图 2024-08-13 160337](https://github.com/user-attachments/assets/64703e8c-17ef-44d9-a187-fe02c72e18b5)

**Comment by axel-loewe** [comment]
I'm not familiar with Abaqus. What you'll need is a tetrahedral mesh in VTK format with the relevant surface elements labeled in a VTK array.
